<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>8cc9a8f0-9a02-43d5-b126-d58cd6705c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='CC'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>3ccf4208-8f10-40ef-a369-b43fb296c6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>3ecf01f3-c78b-4fc8-a382-737137de9370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>2dc81389-f19b-4011-ba65-e6bcd483ad3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>721e9c7c-b20f-4096-8940-388d4768036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 256 256</value>
      <webElementGuid>f747728b-4381-4f12-926b-e4a92ce5b456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>256a995b-db07-486f-8b6c-5f444bfcca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>95d4cd59-df14-43b1-ac7b-c9d6eb52d6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a2985530-f1ba-4ec2-92ff-53e359003a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;min-h-screen bg-[#F8F8F8] font-sans antialiased __variable_0aa786&quot;]/div[@class=&quot;flex flex-col h-screen&quot;]/div[@class=&quot;flex flex-1 overflow-hidden&quot;]/main[@class=&quot;flex flex-1 w-full overflow-y-auto p-4 bg-[#F8F8F8] dark:bg-[#2F3438]&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;flex pb-10&quot;]/div[@class=&quot;flex flex-col md:w-1/3 mx-6&quot;]/div[@class=&quot;sticky top-0 left-0 flex flex-col gap-2 bg-white dark:bg-gray-600 rounded-2xl shadow p-6&quot;]/div[3]/div[@class=&quot;rounded-lg p-4 flex items-center mb-2 bg-white dark:bg-[#2f3339]&quot;]/div[@class=&quot;flex flex-col flex-grow&quot;]/div[@class=&quot;flex gap-4 mt-3&quot;]/button[1]/button[@class=&quot;inline-flex items-center justify-center whitespace-nowrap rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-10 w-10 text-lg text-green-600 dark:text-green-400&quot;]/svg[1]</value>
      <webElementGuid>2710fcd5-ae37-48a9-a71b-046d2eb2886c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>fc092093-0367-4b39-b016-f2084ca962a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='signer'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>ef6b2cd3-619f-4089-8968-4e9a9d8264d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Now'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>8cbf3b1c-c087-4a30-b2f6-ee72a5df81dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle theme'])[1]/preceding::*[name()='svg'][7]</value>
      <webElementGuid>0f6df8f3-fe7d-4096-ba77-e62f9dfc0dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
